apps/survey/urls.py
from django.conf.urls import patterns, url

from apps.survey.views import *

urlpatterns = patterns('',
    url(r'^ticket$', TicketView.as_view(), name='ticket'),
    url(r'^signup$', SignUpView.as_view(), name='signup'),
    url(r'^signin$', SignInView.as_view(), name='signin'),
    url(r'^signout$', SignOutView.as_view(), name='signout'),
    url(r'^storylines$', StorylinesView.as_view(), name='storylines'),
    url(r'^storylines/(?P<id>\d+)$', UserStoryView.as_view(), name='userstory'),
    url(r'^storylines/(?P<id>\d+)/eval$', EvalStoryView.as_view(), name='evalstory'),
    url(r'^profile$', ProfileInfoView.as_view(), name='profileinfo'),
    url(r'^analysis$', AnalysisView.as_view(), name='analysis'),
    url(r'^terms$', TermsView.as_view(), name='terms'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'storyline.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.search.urls', namespace='search')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/survey/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.search.models import Article

# Create your models here.

class Profile(models.Model):

    N = 'N' # Neither/Other

    M = 'M' # Male
    F = 'F' # Female
    
    H = 'H' # High School
    U = 'U' # Undergraduate degree
    G = 'G' # Master's or doctoral degree
    
    GENDER_CHOICES = (
        (N, 'Neither/Other'),
        (M, 'Male'),
        (F, 'Female'),
    )
    
    EDU_CHOICES = (
        (N, 'Neither/Other'),
        (H, 'High School'),
        (U, 'Undergraduate'),
        (G, 'Graduate'),
    )
    
    AGE_CHOICES = (
        (N, 'Neither/Other'),
        ('ONE', '14 to 18'),
        ('TWO', '19 to 23'),
        ('THR', '24 to 28'),
        ('FOU', '29 to 33'),
        ('FIV', '34 to 38'),
        ('SIX', '39 to 43'),
        ('SEV', '44 to 48'),
        ('EIG', '49 to 53'),
        ('NIN', '54 to 58'),
        ('TEN', '59 or more'),
    )
    
    user = models.OneToOneField(User)
    
    agreed = models.BooleanField(default=False)

    gender = models.CharField(
                            max_length=3,
                            choices=GENDER_CHOICES,
                            default=N
                            )
    edu = models.CharField(
                            max_length=3,
                            choices=EDU_CHOICES,
                            default=N
                            )

    age = models.CharField(
                            max_length=3,
                            choices=AGE_CHOICES,
                            default=N
                            )
    
    def is_filled(self):
        if self.edu != self.N and self.gender != self.N and self.age != self.N:
            return True
        return False
    
    def __unicode__(self):
        return self.user.username

class Ticket(models.Model):

    email = models.EmailField()
    token = models.CharField(max_length=255)


class Story(models.Model):

    first = models.ForeignKey(Article)
    users = models.ManyToManyField(User, through='UserStory')
    
    def first_story_id(self):
        return str(self.first.id)
    first_story_id.short_description = 'First Story ID'
    
    def __unicode__(self):
        return self.first.title


class StoryRank(models.Model):

    story = models.ForeignKey(Story)
    article = models.ForeignKey(Article)
    rank = models.IntegerField()

    def first_story_id(self):
        return str(self.story.first.id)
    first_story_id.short_description = 'First Story ID'
    
    def __unicode__(self):
        return str(self.story.first.id)

class UserStory(models.Model):
    N = 'N'
    YES = 'YES'
    NO = 'NO'
    
    BOOLEAN_CHOICES = (
        (N, 'Neither/Other'),
        (YES,'Yes'),
        (NO,'No')
    )
    
    user = models.ForeignKey(User)
    story = models.ForeignKey(Story)
    
    # eval
    has_read = models.CharField(max_length=3,choices=BOOLEAN_CHOICES, default=N)
    has_context = models.CharField(max_length=3,choices=BOOLEAN_CHOICES, default=N)
    has_gap = models.CharField(max_length=3,choices=BOOLEAN_CHOICES, default=N)
    has_similar = models.CharField(max_length=3,choices=BOOLEAN_CHOICES, default=N)
    
    class Meta:
        unique_together = (('user', 'story'),)

    def __unicode__(self):
        return "%s : %s" % (self.user.username, self.story.first.title)

class UserStoryRank(models.Model):

    userstory = models.ForeignKey(UserStory)
    article = models.ForeignKey(Article)
    rank = models.IntegerField()

    def first_story_id(self):
        return str(self.userstory.story.first.id)
    first_story_id.short_description = 'First Story ID'
    
    def __unicode__(self):
        return str(self.article.id)

apps/survey/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import widgets

from captcha.fields import ReCaptchaField
from models import *

class SignUpForm(forms.Form):

    email = forms.EmailField()
    passphrase = forms.CharField(widget=forms.PasswordInput())
    agreed = forms.BooleanField()
    captcha = ReCaptchaField(attrs={'theme' : 'clean'})
    ticket = forms.CharField()
    
    email.widget.attrs['class'] = 'form-control text-center'
    email.widget.attrs['placeholder'] = 'seu_email@exemplo.com'

    passphrase.widget.attrs['class'] = 'form-control text-center'
    passphrase.widget.attrs['placeholder'] = 'senha'
    
    ticket.widget.attrs['class'] = 'form-control text-center'
    ticket.widget.attrs['placeholder'] = 'ticket'
    
class SignInForm(forms.Form):

    email = forms.EmailField()
    passphrase = forms.CharField(widget=forms.PasswordInput())
    captcha = ReCaptchaField(attrs={'theme' : 'clean'})
    
    email.widget.attrs['class'] = 'form-control text-center'
    email.widget.attrs['placeholder'] = 'seu_email@exemplo.com'

    passphrase.widget.attrs['class'] = 'form-control text-center'
    passphrase.widget.attrs['placeholder'] = 'senha'

class TicketForm(forms.Form):
    
    email = forms.EmailField()
    captcha = ReCaptchaField(attrs={'theme' : 'clean'})
    
    email.widget.attrs['class'] = 'form-control text-center'
    email.widget.attrs['placeholder'] = 'seu_email@exemplo.com'


class ProfileForm(forms.Form):

    # profile
    age = forms.ChoiceField(choices=Profile.AGE_CHOICES, label="Faixa etária", required=False)
    edu = forms.ChoiceField(choices=Profile.EDU_CHOICES, label="Educação", required=False)
    gender = forms.ChoiceField(choices=Profile.GENDER_CHOICES, label="Gênero", required=False)

class EvalForm(forms.Form):
    # user story

    has_read = forms.ChoiceField(choices=UserStory.BOOLEAN_CHOICES, required=False,label="Já leu ou ouviu falar sobre este tópico antes?")
    has_context = forms.ChoiceField(choices=UserStory.BOOLEAN_CHOICES, required=False,label="De uma maneira geral, a storyline satisfaz a hipótese?")
    has_gap = forms.ChoiceField(choices=UserStory.BOOLEAN_CHOICES, required=False,label="Há a impressão de que falta alguma notícia na storyline?")
    has_similar = forms.ChoiceField(choices=UserStory.BOOLEAN_CHOICES, required=False,label="A storyline tem notícias similares?")

apps/survey/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.utils.decorators import method_decorator
from django.db import IntegrityError

from passlib.hash import sha512_crypt

from apps.survey.forms import *
from apps.survey.models import *
from apps.search.models import *
from project import settings
from apps.engine.chaining import lineup
from scipy.stats import spearmanr
import numpy as np

import os, json

# Create your views here.

MSG_FORM_INVALID = "Ops! Verifique se algum campo do formulário não foi preenchido."

class TicketView(View):
    """
    Ticket View
    
    User requests a ticket to be able to sign up.
    """
    
    MSG_TICKET_EXCEPTION = "Não foi possível enviar o ticket agora. Por favor, tente mais tarde."
    
    def get(self, request):
        
        if request.user.is_authenticated():
            messages.info(request, "Você já entrou na conta de participação.")
            return redirect(reverse('survey:storylines'))
            
        data = {'form': TicketForm()}
        
        return render(request, 'survey/ticket.html', data)
    
    def post(self, request):
        
        # Get filled form data.
        form = TicketForm(request.POST)
        data = {'form': form}
        
        if form.is_valid():
            
            user_email = request.POST.get('email')

            # Get ticket related to user's e-mail.
            try:
            
                ticket = Ticket.objects.get(email=user_email)
            
            except Ticket.DoesNotExist:
            
                # Generate a new token.
                user_token = sha512_crypt.encrypt(user_email)
                
                # Create a new ticket.
                try:
                
                    ticket = Ticket(email=user_email, token=user_token)
                
                except Exception:
                
                    # Ticket has not generated for some reason.
                    messages.error(request, self.MSG_TICKET_EXCEPTION, extra_tags='danger')
                    
                    return render(request, 'survey:ticket', data)
                
                else:
                
                    #Ticket has been generated.
                    
                    # Send ticket's e-mail
                    
                    subject = "Storyline ticket"
                    
                    # Open ticket's file.
                    try:
                        
                        filepath = os.path.join(settings.BASE_DIR, "ticket.txt")
                        f = open(filepath)
                    
                    except Exception:
                    
                        # Ticket's message has not been read.
                        messages.error(request, self.MSG_TICKET_EXCEPTION, extra_tags='danger')
                        
                        return render(request, 'survey:ticket', data)
                    
                    else:
                    
                        message = f.read().replace("<token>", user_token)
                    
                    finally:
                    
                        f.close()
                    
                    try:
                    
                        storyline_email = settings.EMAIL_HOST_USER
                    
                    except Exception:
                    
                        # E-mail sender is not correct.
                        messages.error(request, self.MSG_TICKET_EXCEPTION, extra_tags='danger')
                        
                        return render(request, 'survey:ticket', data)
                        
                    try:
                    
                        send_mail(subject, message, storyline_email, [user_email], fail_silently=True)
                    
                    except Exception:
                        
                        # Something went wrong when sending the e-mail.
                        messages.error(request, self.MSG_TICKET_EXCEPTION, extra_tags='danger')
                        
                        return render(request, 'survey:ticket', data)
                    
                    else:
                    
                        msg = "Um ticket foi enviado para %s." % str(user_email)
                        messages.info(request, msg, extra_tags='info')
                        ticket.save()
                        
                        return redirect(reverse('survey:signup'))
                        
            else:
            
                msg = "Um ticket já foi enviado para %s. Por favor, use outro e-mail." % str(user_email)
                messages.error(request, msg, extra_tags='danger')
                
                return redirect(reverse('survey:ticket'))
                
        else:
        
            # Form is invalid.
            messages.error(request, MSG_FORM_INVALID, extra_tags='danger')
            
            return render(request,'survey/ticket.html', data)

class SignUpView(View):
    """
    Signup View
    
    User sign up to be able to sign in and get started with the survey.
    """
    
    MSG_SIGNUP_EXCEPTION = "Não foi possível criar a sua conta. Tente mais tarde."
    
    def get(self, request):


        if request.user.is_authenticated():
            messages.info(request, "Você já entrou na conta de participação.")
            return redirect(reverse('survey:storylines'))
        
        data = {'form' : SignUpForm()}

        return render(request, 'survey/signup.html', data)

    def post(self, request):
        
        form = SignUpForm(request.POST)
        data = {'form' : form}
        
        if form.is_valid():
            
            user_ticket = request.POST.get('ticket')
            user_email = request.POST.get('email')
            user_passphrase = request.POST.get('passphrase')
            user_agreed = request.POST.get('agreed')
            
            if not user_agreed:
                msg = "Não faz sentido criar uma conta de participação se você não concorda com os termos de participação."
                messages.error(request, msg, extra_tags='danger')
                return redirect(reverse('survey:signup'))
            
            # Get user's ticket
            try:
                
                ticket = Ticket(token=user_ticket)
            
            except Ticket.DoesNotExist:
                
                msg = "Ticket inválido!"
                messages.error(request, msg, extra_tags='danger')
                return render(request, 'survey/signup.html', data)
            
            try:
            
                user_object = User.objects.create_user(
                                                    username=user_email,
                                                    email=user_email,
                                                    password=user_passphrase)
            
            except IntegrityError:
            
                messages.error(request, "Email já cadastrado!", extra_tags='danger')
                
                return render(request, 'survey/signup.html', data)
            
            except Exception:
            
                messages.error(request, self.MSG_SIGNUP_EXCEPTION, extra_tags='danger')
                
                return render(request, 'survey/signup.html', data)
            
            else:
            
                try:
                
                    user_profile = Profile(user=user_object, agreed=user_agreed)
                
                except Exception:
                
                    messages.error(request, self.MSG_SIGNUP_EXCEPTION, extra_tags='danger')
                    
                    return render(request, 'survey/signup.html', data)
                
                else:
                
                    user_profile.save()
                    messages.info(request, "Conta de participação criada com sucesso!", extra_tags='info')
                    
                    stories = Story.objects.all()
                    for story in stories:
                        UserStory.objects.create(user=user_object, story=story)
            
                    return redirect(reverse('survey:signin'))
        else:
        
            messages.error(request, MSG_FORM_INVALID, extra_tags='danger')
            
            return render(request, 'survey/signup.html', data)

class SignInView(View):
    
    MSG_SIGNIN_EXCEPTION = "Não foi possível entrar com a sua conta. Tente mais tarde."
    
    def get(self, request):
    
        if request.user.is_authenticated():
            messages.info(request, "Você já entrou na conta de participação.")
            return redirect(reverse('survey:storylines'))
        
        data = {'form' : SignInForm()}
        
        return render(request, 'survey/signin.html', data)

    def post(self, request):

        form = SignInForm(request.POST)
        data = {'form' : form}

        if form.is_valid():
        
            user_email = request.POST.get('email')
            user_passphrase = request.POST.get('passphrase')
        
            user = authenticate(username=user_email, password=user_passphrase)
        
            if user is not None:
            
                if user.is_active:
                    
                    login(request, user)
                    
                    return redirect(reverse('survey:storylines'))
                
                else:
                
                    messages.error(request, self.MSG_SIGNIN_EXCEPTION, extra_tags='danger')

apps/survey/templates/survey/analysis.html
{% extends "base.html" %}

{% block body %}

<a href="{% url 'survey:storylines' %}" class="btn btn-primary btn-lg pull-right">Avaliar outra storyline</a>

<p class="lead">
    Storyline
</p>


        <div id="spearman"></div>
        Storylines que tendem a 1 validam a hipótese. Storylines que tendem a -1 invalidam a hipótese.
<div class="row">

    <div class="col-md-6 col-lg-6">
            <div id="hasread"></div>
    </div>
    <div class="col-md-6 col-lg-6">
        <div id="hascontext"></div>
    </div>

</div>

<div class="row">
    <div class="col-md-6 col-lg-6">
        <div id="hasgap"></div>
    </div>
    <div class="col-md-6 col-lg-6">
        <div id="hassimilar"></div>
    </div>
</div>

<p class="lead">
    Perfil
</p>
<div class="row">
    <div class="col-md-6 col-lg-6">
        <div id="gender"></div>
    </div>
    <div class="col-md-6 col-lg-6">
        <div id="age"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-lg-6">
        <div id="edu"></div>
    </div>
    <div class="col-md-6 col-lg-6"></div>
</div>

{% endblock %}

{% block js %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script src="{{ STATIC_URL }}survey/js/analysis.js"></script>
    <script>
        pizza(id='gender', d={{ gender | safe }}, t='Gênero');
        pizza(id='age', d={{ age | safe }}, t='Idade');
        pizza(id='edu', d={{ edu | safe }}, t='Educação');
        pizza(id='hasread', d={{ hasread | safe }}, t='Já Leu ou Ouviu Falar Sobre o Assunto ');
        pizza(id='hascontext', d={{ hascontext | safe }}, t='De Uma Maneira Geral, a Storyline Atende a Hipótese');
        pizza(id='hasgap', d={{ hasgap | safe }}, t='Teve a Impressão de que Faltam Notícias na Storyline');
        pizza(id='hassimilar', d={{ hassimilar | safe }}, t='Existem Notícias Similares');
        barchart(id='spearman', d={{ spearman | safe }}, t='Coeficiente de Correlação de Spearman Médio (CCSM)')
        
    </script>
{% endblock %}

apps/survey/templates/survey/article_story.html
{% if doc %}
    <h3>
        <a href="{{ doc.url }}" target="_blank">{{ doc.title }}</a><br>
    </h3>
    <!--{#<small><span class="text-muted pull-right">{{ doc.source }} - {{ doc.pub_date|date:"d/m/Y H:i" }}</span></small>#}--><br>
    <!--<small class="text-success">{{ doc.url }}</small><br>-->
    <span class="text-justify">{{ doc.body|truncatewords_html:300|safe }}</span><br>
    <small>Notícia completa em <a href="{{ doc.url }}" target="_blank"><strong>{{ doc.source }}</strong></a>.</small>
{% else %}
    <p class="text-center">Não foi possível recuperar este documento.</p>
{% endif %}

apps/survey/templates/survey/eval_story.html
{% extends "base.html" %}



{% block body %}

<div class="row">
<div class="col-md-6 col-lg-6">
    <p class="lead">Sua Storyline<br>
    
        </p>
    </div>

    <div class="col-md-6 col-lg-6">
        <p class="lead">Storyline original<br>
        
        </p>
    </div>
    </div>
<div class="row">
   
    <div class="col-md-6 col-lg-6">
    
        <ul class="list-unstyled">
            {% for doc in userresults %}
                <li>
                    {% include "survey/snippet_lineup_story.html" with doc=doc.article %}
                </li>
            {% empty %}
            {% endfor %}
        </ul>
    </div>
     <div class="col-md-6 col-lg-6">
        <ul class="list-unstyled">
            {% for doc in results %}
                <li>
                    {% include "survey/snippet_lineup_story.html" with doc=doc.article %}
                </li>
            {% empty %}
            {% endfor %}
        </ul>
    </div>
    
</div>
<div class="row">

    <div class="col-md-7 col-lg-7">
        <div id="results"></div>
    </div>
    
    <div class="col-md-5 col-lg-5">
         <p class="lead">
            Avaliação da Storyline ORIGINAL<br>
            <small><small>
                Por favor, avalie a storyline ao lado.<br>
                <strong>
                    (Você está avaliando a storyline original)
                </strong>
            </small></small>
        </p>
        
        <form action="#" method="post" role="form">{% csrf_token %}
            
            {{ eval_form.as_p }}
            
        
            <input type="submit" class="btn btn-block btn-primary" value="Enviar">
        </form>
    </div>

</div>

{% endblock %}



{% block js %}
	<script src="{{ STATIC_URL }}search/js/search.js"></script>
{% endblock %}

apps/survey/templates/survey/profile_info.html
{% extends "base.html" %}


{% block body %}

<div class="row">

<div class="col-md-5 col-lg-5">
    <form action="#" method="post" role="form">{% csrf_token %}
        <p class="lead">
            Perfil<br>
            <small><small>Por favor, complemente as informações do seu perfil de participante.</small></small>
        </p>
    
        {{ profile_form.as_p }}
        <input type="submit" class="btn btn-block btn-primary" value="Enviar">
    </form>
</div>
</div>
    
{% endblock %}

apps/survey/templates/survey/signin.html
{% extends "base.html" %}
{% load webdesign %}

{% block title %}
Sign in
{% endblock %}



{% block body %}
<div class="row">
    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <form action="{% url 'survey:signin' %}" method="post" role="form">{% csrf_token %}
            <div class="well">
                {{ form.non_field_errors }}
                <div class="form-group">
                    <p class="text-right">
                        Ainda não se cadastrou? Solicite um <a href="{% url 'survey:ticket' %}">ticket</a> para se cadastrar.
                    </p>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-1 col-lg-offset-1">
                        {{ form.captcha.errors }}
                        {{ form.captcha }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.email.errors }}
                    {{ form.email }}
                </div>
                <div class="form-group">
                    {{ form.passphrase.errors }}
                    {{ form.passphrase }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Entrar" />
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

apps/survey/templates/survey/signup.html
{% extends "base.html" %}

{% block title %}
Sign up
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <form action="{% url 'survey:signup' %}" method="post" role="form">{% csrf_token %}
            <div class="well">
                {{ form.non_field_errors }}
                <div class="form-group">
                    <p class="text-right">
                        Já se cadastrou? <a href="{% url 'survey:signin'%}">Entre agora</a>
                    </p>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-1 col-lg-offset-1">
                        {{ form.captcha.errors }}
                        {{ form.captcha }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.ticket.errors }}
                    {{ form.ticket }}
                </div>
                <div class="form-group">
                    {{ form.email.errors }}
                    {{ form.email }}
                </div>
                <div class="form-group">
                    {{ form.passphrase.errors }}
                    {{ form.passphrase }}
                </div>
                <div class="form-group">
                    {{ form.agreed.errors }}
                    {{ form.agreed }} Li e aceito o termo de participação do survey.
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Participar" />
                </div>
            </div>
        </form>
    </div>
</div>
<br><br>
<p class="text-center">
Se o ticket não chegar em seu e-mail, em no máximo 5 minutos, envie um e-mail para Phillipe Cavalcante com o assunto "Storyline Ticket":<br>
e-mail:<code> &lt;sobrenome&gt;&lt;ponto&gt;&lt;nome&gt;&lt;at&gt;gmail&lt;ponto&gt;com</code>
</p>
{% endblock %}

apps/survey/templates/survey/snippet_lineup_story.html
<a href="#" onclick="getArticle('{{ doc.id }}', 1);">{{ doc.title }}</a><br>{% csrf_token %}
<!--<small class="text-success">{{ doc.url }}</small><br>-->
<!--<small class="text-justify">{{ doc.body|truncatewords_html:30|striptags|safe }}</small><br>-->
<!--{# <small><span class="text-muted pull-right">{{ doc.source }} - {{ doc.pub_date|date:"d/m/Y H:i" }}</span></small> #}-->
<hr class="softlen">

apps/survey/templates/survey/snippet_story.html
<a href="{% url 'survey:userstory' doc.id %}">{{ doc.first.title }}</a><br>
<!--<small class="text-success">{{ doc.url }}</small><br>-->
<!--<small class="text-justify">{{ doc.body|truncatewords_html:30|striptags|safe }}</small><br>-->
<small><span class="text-muted pull-right">{{ doc.first.source }} - {{ doc.first.pub_date|date:"d/m/Y H:i" }}</span></small>
<hr class="softlen">

apps/survey/templates/survey/storylines.html
{% extends "base.html" %}

{% block title %}Storylines{% endblock %}

{% block body %}

<div class="row">
    <div class="col-md-7 col-md-offset-2 col-lg-7 col-lg-offset-2">
        <p class="lead">
            Escolha uma notícia para avaliação:<br>
        </p>
    </div>
</div>

<div class="col-md-7 col-md-offset-2 col-lg-7 col-lg-offset-2">
    {% for doc in results %}
        {% include "survey/snippet_story.html" %}
    {% endfor %}
</div>

{% endblock %}

apps/survey/templates/survey/subscribe.html
{% extends "base.html" %}
{% load webdesign %}

{% block title %}
Subscribe
{% endblock %}

{% block body %}
{{x}}

<div class="row">
    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <p class="lead">Termo de Participação</p>
        <div class="text-justify">{% lorem 3 p %}</div>
        <form action="{% url 'survey:subscribe' %}" method="post" role="form">{% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                <div class="col-md-offset-1 col-lg-offset-1">
                    {{ form.captcha.errors }}
                    {{ form.captcha }}
                </div>
            </div>
            <div class="well">
                <div class="form-group">
                    {{ form.email.errors }}
                    {{ form.email }}
                </div>
                <div class="form-group">
                    {{ form.agreed.errors }}
                    {{ form.agreed }} Li e aceito o termo de participação do survey.
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Participar" />
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

apps/survey/templates/survey/ticket.html
{% extends "base.html" %}
{% load webdesign %}

{% block title %}
Ticket
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <form action="{% url 'survey:ticket' %}" method="post" role="form">{% csrf_token %}
            <div class="well">
                {{ form.non_field_errors }}
                <div class="form-group">
                    <div class="col-md-offset-1 col-lg-offset-1">
                        {{ form.captcha.errors }}
                        {{ form.captcha }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.email.errors }}
                    {{ form.email }}
                </div>
            </div>
            <div class="form-group">
            <p class="text-justify">
                Leia os <a href="{% url 'survey:terms' %}">termos de participação</a> do survey antes de enviar o ticket para o seu e-mail.
            </p>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Enviar ticket" />
                </div>
            </div>
           
        </form>
        

    </div>
</div>
{% endblock %}