apps/search/urls.py
from django.conf.urls import patterns, url

from apps.search.views import *

DOC  = '(?P<id>\d+)'
LINE = '(?P<line>(timeline|relevance))'
METH = '(?P<meth>(tf-idf|bm25f))'
ART  = 'article'

SEARCH    = '^' + '$'
STORYLINE = '^' + DOC + '$'
LINEUP    = '^' + DOC + '/' + LINE + '/' + METH + '$'
ARTICLE   = '^' + ART + '/' + '$'

urlpatterns = patterns('',
    url(SEARCH   , SearchView.as_view()   , name='search'),
    url(STORYLINE, StorylineView.as_view(), name='storyline'),
    url(LINEUP   , LineUpView.as_view()   , name='lineup'),
    url(ARTICLE  , ArticleView.as_view()  , name='article'),
)

apps/survey/urls.py
from django.conf.urls import patterns, url

from apps.survey.views import *

urlpatterns = patterns('',
    url(r'^ticket$', TicketView.as_view(), name='ticket'),
    url(r'^signup$', SignUpView.as_view(), name='signup'),
    url(r'^signin$', SignInView.as_view(), name='signin'),
    url(r'^signout$', SignOutView.as_view(), name='signout'),
    url(r'^storylines$', StorylinesView.as_view(), name='storylines'),
    url(r'^storylines/(?P<id>\d+)$', UserStoryView.as_view(), name='userstory'),
    url(r'^storylines/(?P<id>\d+)/eval$', EvalStoryView.as_view(), name='evalstory'),
    url(r'^profile$', ProfileInfoView.as_view(), name='profileinfo'),
    url(r'^analysis$', AnalysisView.as_view(), name='analysis'),
    url(r'^terms$', TermsView.as_view(), name='terms'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'storyline.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.search.urls', namespace='search')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
    
        <!--CSS-->
        <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}storyline/css/storyline.css" rel="stylesheet">
        {% block css %}{% endblock %}
        <!--link rel="shortcut icon" href="../../assets/ico/favicon.ico"-->
        <!--/-->
        
        <title>{% block title %}Storyline{% endblock %}</title>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                {% include "brand.html" %}
            </div>
        </nav>
        
        <div class="container">
            {% for message in messages %}
                <div {% if message.tags %}class="alert alert-{{ message.tags }} alert-dismissable"{% endif %}>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
            {% empty %}
            {% endfor %}
        </div>
        
        {% block header %}{% endblock %}
        
        <div class="container">
            {% block body %}{% endblock %}
        </div>
        
        <div class="container">
            <ul class="list-inline">
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'survey:ticket' %}">Participe do Survey</a></li>
                {% endif%}
            </ul>
        </div>
        <!--JS-->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
        <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
        <script src="{{ STATIC_URL }}storyline/js/ajax.js"></script>
        <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52633512-1', 'auto');
  ga('send', 'pageview');

</script>
        {% block js %}{% endblock %}
        <!--/JS-->
    </body>
</html>

templates/brand.html
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
<a class="navbar-brand" href="{% url 'search:search' %}">Storyline</a>
</div>

<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
    <li class="active"><a href="{% url 'survey:storylines' %}">Survey</a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Participante #{{ user.id }}<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <!--li class="divider"></li-->
            <li><a href="{% url 'survey:profileinfo' %}">Perfil</a></li>
            <li><a href="{% url 'survey:signout' %}">Sair</a></li>
        </ul>
    </li>
    {% else %}
        <li><a href="{% url 'survey:signin' %}">Entrar</a></li>
    {% endif %}
</ul>