apps/search/urls.py
from django.conf.urls import patterns, url

from apps.search.views import *

DOC  = '(?P<id>\d+)'
LINE = '(?P<line>(timeline|relevance))'
METH = '(?P<meth>(tf-idf|bm25f))'
ART  = 'article'

SEARCH    = '^' + '$'
STORYLINE = '^' + DOC + '$'
LINEUP    = '^' + DOC + '/' + LINE + '/' + METH + '$'
ARTICLE   = '^' + ART + '/' + '$'

urlpatterns = patterns('',
    url(SEARCH   , SearchView.as_view()   , name='search'),
    url(STORYLINE, StorylineView.as_view(), name='storyline'),
    url(LINEUP   , LineUpView.as_view()   , name='lineup'),
    url(ARTICLE  , ArticleView.as_view()  , name='article'),
)

apps/survey/urls.py
from django.conf.urls import patterns, url

from apps.survey.views import *

urlpatterns = patterns('',
    url(r'^ticket$', TicketView.as_view(), name='ticket'),
    url(r'^signup$', SignUpView.as_view(), name='signup'),
    url(r'^signin$', SignInView.as_view(), name='signin'),
    url(r'^signout$', SignOutView.as_view(), name='signout'),
    url(r'^storylines$', StorylinesView.as_view(), name='storylines'),
    url(r'^storylines/(?P<id>\d+)$', UserStoryView.as_view(), name='userstory'),
    url(r'^storylines/(?P<id>\d+)/eval$', EvalStoryView.as_view(), name='evalstory'),
    url(r'^profile$', ProfileInfoView.as_view(), name='profileinfo'),
    url(r'^analysis$', AnalysisView.as_view(), name='analysis'),
    url(r'^terms$', TermsView.as_view(), name='terms'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'storyline.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.search.urls', namespace='search')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/search/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.

class Article(models.Model):

    source = models.CharField(max_length=255)
    url = models.URLField()
    title = models.CharField(max_length=255)
    pub_date = models.DateTimeField(auto_now_add=False)
    description = models.TextField()
    body = models.TextField()
    links = models.TextField()

    def __unicode__(self):
        return "%s - %s" % (self.id, self.title)

class Topic(models.Model):

    name = models.CharField(max_length=255)
    terms = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

apps/search/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import widgets


class SearchForm(forms.Form):

    search = forms.CharField()

    search.widget.attrs['class'] = 'form-control'

apps/search/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.views.generic import View
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
#from django.core.urlresolvers import reverse

from apps.search.forms import SearchForm
from apps.search.models import Topic, Article
from apps.engine.query import parse
from apps.engine.searcher import get_searcher
from apps.engine.index import get_index
from whoosh import sorting
from apps.engine.chaining import lineup, storyline
# Create your views here.

class SearchView(View):

    def get(self, request):
    
    
        count_docs = Article.objects.all().count()
        
        data = {'form' : SearchForm(),
                'countdocs' : count_docs}
        
        
        
        try:
            topics = Topic.objects.all().order_by('name')
        except Exception:
            pass
        else:
            data.update({'topics': topics})
        
        
        return render(request, 'search/search.html', data)

    def post(self, request):

        if request.is_ajax():
        
            query = request.POST.get('query')
            query_parsed = parse(query)
            
            try:
                page = request.POST.get('page')
                if page is None: page = 1
                page = int(page)
            except ValueError:
                page = 1


            searcher = get_searcher()
            results = searcher.search_page(query_parsed, page, 10)
            hits = len(results)
            
            pages = results.pagecount
            current_page = page
            has_previous = current_page > 1
            has_next = current_page < pages
            previous_page = current_page - 1 if has_previous else None
            next_page = current_page + 1 if has_next else None
            
            paginator = {
                    "pages" : pages,
                    "current_page" : current_page,
                    "has_previous" : has_previous,
                    "has_next" : has_next,
                    "previous_page" : previous_page,
                    "next_page" : next_page,
                }
            
            
            data = {
                    'hits' : hits,
                    'query' : query,
                    'results': results
                    }
            data.update(paginator)
            
            return render(request, 'search/results.html', data)
    
        return redirect(reverse('search:search'))

class StorylineView(View):

    def get(self, request, *args, **kwargs):
        
        doc_id = kwargs.get('id')
        
        results = storyline(doc_id)
        
        data = {
                'initial' : results[0],
                'line' : 'storyline',
                'meth' : 'rte',
                'results' : results,
                }
        
        return render(request, 'search/lineup.html', data)

class LineUpView(View):

    def get(self, request, *args, **kwargs):
        
        line = kwargs.get('line')
        meth = kwargs.get('meth')
        doc_id = kwargs.get('id')
        
        results = lineup(doc_id, line, meth)

        data = {
                'initial' : results[0],
                'line' : line,
                'meth' : meth,
                'results' : results,
                }

        return render(request, 'search/lineup.html', data)


class ArticleView(View):

    def post(self, request, *args, **kwargs):
        
        if request.is_ajax():
        
            data = {}
            
            try:
                doc = Article.objects.get(pk=request.POST.get('id'))
            except Article.DoesNotExist:
                doc = None
            else:
                data.update({'doc' : doc})
            
            isSurvey = bool(int(request.POST.get('isSurvey')))
            if isSurvey:
                return render(request, 'survey/article_story.html', data)
            
            return render(request, 'search/article.html', data)

apps/search/templates/search/article.html
{% if doc %}
    <h3>
        <a href="{{ doc.url }}" target="_blank">{{ doc.title }}</a><br>
    </h3>
    <small><span class="text-muted pull-right">{{ doc.source }} - {{ doc.pub_date|date:"d/m/Y H:i" }}</span></small><br>
    <!--<small class="text-success">{{ doc.url }}</small><br>-->
    <span class="text-justify">{{ doc.body|truncatewords_html:300|safe }}</span><br>
    <small>Notícia completa em <a href="{{ doc.url }}" target="_blank"><strong>{{ doc.source }}</strong></a>.</small>
{% else %}
    <p class="text-center">Não foi possível recuperar este documento.</p>
{% endif %}

apps/search/templates/search/lineup.html
{% extends "base.html" %}


{% block body %}

<div class="row">
    <div class="col-md-12 col-lg-12 col-md-offset-2 col-lg-offset-2">
        <ul class="nav nav-pills">
            <li class="{% if line == 'storyline' and meth == 'rte' %}active{% endif %}">
                <a href="{% url 'search:storyline' id=initial.id %}">storyline / rte</a>
            </li>
            <li class="{% if line == 'relevance' and meth == 'tf-idf' %}active{% endif %}">
                <a href="{% url 'search:lineup' id=initial.id line='relevance' meth='tf-idf'%}">relevance / tf-idf</a>
            </li>
            <li class="{% if line == 'relevance' and meth == 'bm25f' %}active{% endif %}">
                <a href="{% url 'search:lineup' id=initial.id line='relevance' meth='bm25f'%}">relevance / bm25f</a>
            </li>
            <li class="{% if line == 'timeline' and meth == 'tf-idf' %}active{% endif %}">
                <a href="{% url 'search:lineup' id=initial.id line='timeline' meth='tf-idf'%}">timeline / tf-idf</a>
            </li>
            <li class="{% if line == 'timeline' and meth == 'bm25f' %}active{% endif %}">
                <a href="{% url 'search:lineup' id=initial.id line='timeline' meth='bm25f'%}">timeline / bm25f</a>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-7 col-lg-7">
        <div id="results">
            {% include "search/article.html" with doc=initial %}
        </div>
    </div>
    <div class="col-md-5 col-lg-5" style="padding-top:25px">
        <p class="lead">
            Notícias Relacionadas
            (<small> {{ line }} / {{ meth }} </small>)
        </p>
        {% for doc in results %}
            {% include "search/snippet_lineup.html" %}
        {% empty %}
        {% endfor %}
    </div>
</div>

{% endblock %}


{% block js %}
	<script src="{{ STATIC_URL }}search/js/search.js"></script>
{% endblock %}

apps/search/templates/search/results.html
{% if query %}
    <p class="text-muted">
        <strong>{{ hits }}</strong> resultados para <strong>"{{ query }}"</strong>.
    </p>
{% endif %}

<div>
    
    {% for doc in results %}
        {% include "search/snippet.html" %}
    {% empty %}
    {% endfor %}
</div>

{% if results %}
    <div class="pagination">
        <ul class="pager">
            {% if has_previous %}
                <li>
                    <a href="#" onclick="sendPage({{ previous_page }})">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                </li>
            {% endif %}
            <span class="current">
                Página {{ current_page }} de {{ pages }}
            </span>

            {% if has_next %}
                <li>
                    <a href="#" onclick="sendPage({{ next_page }})">                                                <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}

<!--{#
{% if results %}
    <div class="pagination">
        <ul class="pager">
            {% if results.has_previous %}
                <li>
                    <a href="#" onclick="sendPage({{ results.previous_page_number }})">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                </li>
            {% endif %}

            <span class="current">
                Página {{ results.number }} de {{ results.paginator.num_pages }}
            </span>

            {% if results.has_next %}
                <li>
                    <a href="#" onclick="sendPage({{ results.next_page_number }})">                                                <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}
#}-->

apps/search/templates/search/search.html
{% extends "base.html" %}


{% block header %}

<div class="container">
    <div class="row">
        <div class="col-md-7 col-lg-7">
            <!--form action="" method="post" role="form"-->{% csrf_token %}
                <div style="padding-top:5px;">
                    {{ form.non_field_errors }}
                    <!--<div class="form-group">-->
                        {{ form.search.errors }}
                        {{ form.search }}
                    <!--</div>-->
                </div>
            <!--/form-->
            <small><span class="text-muted pull-right">{{ countdocs }} documentos indexados.</span></small>
        </div>
        <div class="col-md-5 col-lg-5">
            {% if not user.is_authenticated %}
              <a href="{% url 'survey:ticket' %}" class="btn btn-warning pull-right" role="button">Participe do Survey</a>
            {% endif %}
        </div>
    </div>
</div>

<hr class="softlen">

<div class="container">
    <div class="row">
        <div class="col-md-7 col-lg-7">
            <div id="results">
                {% include "search/results.html" %}
            </div>
        </div>
        <div class="col-md-5 col-lg-5">
            {% if topics %}
            <section>
                <h3>Tópicos</h3>
                <p class="text-muted"><small>Alguns tópicos existentes aqui.</small></p>
                <ul class="list-unstyled">
                    {% for topic in topics %}
                        <li><a href="#" onclick="searchTopic('{{ topic.terms }}');">{{ topic }}</a></li>
                    {% empty %}
                    {% endfor %}
                </ul>
            </section>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
	<script src="{{ STATIC_URL }}search/js/search.js"></script>
{% endblock %}

apps/search/templates/search/snippet.html
<a href="{% url 'search:storyline' doc.id %}">{{ doc.title }}</a><br>
<small class="text-success">{{ doc.url }}</small><br>
<small class="text-justify">{{ doc.body|truncatewords_html:30|striptags|safe }}</small><br>
<small><span class="text-muted pull-right">{{ doc.source }} - {{ doc.pub_date|date:"d/m/Y H:i" }}</span></small>
<hr class="softlen">

apps/search/templates/search/snippet_lineup.html
<a href="#" onclick="getArticle('{{ doc.id }}', 0);">{{ doc.title }}</a><br>{% csrf_token %}
<!--<small class="text-success">{{ doc.url }}</small><br>-->
<!--<small class="text-justify">{{ doc.body|truncatewords_html:30|striptags|safe }}</small><br>-->
<small><span class="text-muted pull-right">{{ doc.source }} - {{ doc.pub_date|date:"d/m/Y H:i" }}</span></small>
<hr class="softlen">